### ISSUE TITLE
Greyscale output

### ISSUE THREAD

**Issue by mkeller-ergon** [4lex4/scantailor-advanced#10]
I scan a lot of books with greyscale pictures. However, ST only outputs either Black&White (1bit) output or full 24bit output if the input files are 24bit as well.
So currently I have to convert all scans to greyscale BEFORE importing them into ST if I want pages with pictures to be produced in greyscale as well.
It would be nice if greyscale output could be selected in addition to 1bit and 24bit to do it directly from the workflow. This would be especially interesting for projects with mixed colored and greyscale images to avoid having to selectively convert the pages before or after ST.
Also the dropdown concerning the adjustment of the colors is misleading with greyscale input: I have to select the option for COLOR input in order to have the pictures adjusted in their brightness which is a bit misleading. Perhaps it should just explicitly say that it's for color and greyscale (in contrast to the other option being for pure black and white)

**Comment by 4lex4** [comment]
Just use any image editor supporting batch processing for that task. I don't implement features duplicating the functional of image editors. 
Also if you work with gray images, you should apply other filters such as auto-level, background cleaning and smoothing & unsharpen mask (I can give you a useful link to Photoshop actions I've made and use), or you'll get a bad for reading result with ineffective compression level in any container (pdf, djvu e. t. c.). I.e you need graphical editor anyway to get good results working with greyscale / color, use of only ST is not enough.
