### ISSUE TITLE
[enhancement] better deskew GUI

### ISSUE THREAD

**Issue by AlexJacobs1977** [4lex4/scantailor-advanced#100]
I really love scan tailor advanced. Thank you for developping it further. 
I would like to make a suggestion regarding the deskew strep. Sometimes I have difficulty seeing the grid against the picture because of the thin lines. I would love an option to show thicker lines. Although I really like the blue, it is sometimes difficult to see it against the picture, an option to change the color would be very welcome.

**Comment by zvezdochiot** [comment]
Isn't it better to be able to (optionally) look at the image in CONTOUR (edge filter) mode.

**Comment by AlexJacobs1977** [comment]
I'm having trouble find the CONTOUR (edge filter) mode. I'm using scan tailor advanced 1.0.16 for windows.

**Comment by zvezdochiot** [comment]
No problem. There is no such filter yet. This is just an offer to replace yours.

**Comment by AlexJacobs1977** [comment]
Than it is impossible for me to judge if CONTOUR (edge filter) is better or worse, compared with deskew mode.

**Comment by zvezdochiot** [comment]
This is not a replacement for deskew, it is a mod that puts your image in COUNTOUR mode, which improves your alignment capabilities.

**Comment by rbrito** [comment]
Which mod is that?

**Comment by zvezdochiot** [comment]
@rbrito say:
>Which mod is that?

Nothing. Not done yet. And it is unlikely to be.

**Comment by 4lex4** [comment]
Duplicates #90
