### ISSUE TITLE
[enhancement] option for transparent output

### ISSUE THREAD

**Issue by AlexJacobs1977** [4lex4/scantailor-advanced#102]
Thank you for scantailor advanced. I really enjoy using your program.
For text, I don't have an issue, it's perfect. For drawings, I really would love a different strategy, the ability to make the output (tiff) transparent where the pixels are white. The reasoning behind is that on a tablet, the white color can be overwhelming when reading an epub. When making a picture transparent, the user is not overwhelmed, since the color (or pattern) of the background (which is less obtrusive) is taken.

**Comment by zvezdochiot** [comment]
See https://github.com/4lex4/scantailor-advanced/issues/101#issuecomment-611980644

**Comment by AlexJacobs1977** [comment]
TIFF can also have transparent layers, mind you.

**Comment by 4lex4** [comment]
Just replace `#FFFFFF` color with transparent in magick or any other image editor with batch processing support
