### ISSUE TITLE
Selects the image area with a rectangular frame.

### ISSUE THREAD

**Issue by d4fe** [4lex4/scantailor-advanced#108]
Please make the selection of the image area a rectangular frame (when manually editing the area in processing mode "Mixed"). (Automatic translation).

**Comment by Piolie** [comment]
It's already implemented. Simply hold `Ctrl` while creating or editing the zone. [(New zone interaction modes)](https://github.com/4lex4/scantailor-advanced#new-zone-interaction-modes)

**Comment by d4fe** [comment]
Understood thanks!
