### ISSUE TITLE
Asterisks after useful area processing

### ISSUE THREAD

**Issue by d4fe** [4lex4/scantailor-advanced#115]
After processing the useful area, some pages are not marked with asterisks. What does it mean?
(Automatic translation).

**Comment by Piolie** [comment]
The [README](https://github.com/4lex4/scantailor-advanced/blob/master/README.md#scantailor-advanced-fixes--improvements), says

> Added option to control highlighting the thumbnails of pages with high deviation with red asterisks. The option refreshes the thumbnails instantly.

Basically, you get red asterisks for each page that deviates more that a certain angle, content area or margin size. You can control the threshold in `Tools -> Settings -> Processing -> Deviation`.

![asterisk](https://user-images.githubusercontent.com/20274082/79907341-d27c3800-83ef-11ea-847d-851cce21a3a2.png)

Personally, I haven't found it too useful.

**Comment by d4fe** [comment]
And in what units of measurement are the deviations in the settings?

**Comment by Piolie** [comment]
For `Deskew` (which, by the way, I just noticed says `Deksew` in the above menu) I think it's sexagesimal degrees, the same units that step 3 uses. The others I really don't know.
