### ISSUE TITLE
What is the recognition zone for?

### ISSUE THREAD

**Issue by d4fe** [4lex4/scantailor-advanced#116]
What is the recognition zone for? When is this feature useful?
(Automatic translation).

**Comment by Piolie** [comment]
The automatic translation is not helping here. What is the "recognition zone"? To which step are you referring?

**Comment by d4fe** [comment]
![111](https://user-images.githubusercontent.com/63813115/79910711-3292ce80-8430-11ea-85d8-0b98d19eecb3.png)

**Comment by d4fe** [comment]
That is, this is the zone with which the program works, and everything else just forms from consideration?

**Comment by Piolie** [comment]
I had to experiment a while to figure out how it works.

The `Page Box` draws an orange rectangle that represents the physical page. That is, the page contents + white margins. The `Content Box` is the blue rectangle that indicates where the content (text + drawings) is located in the page.

As jeremydmoore said, if each rectangle is correctly positioned and `Auto Margins` from step 5 is activated, STA produces a page that closely matches the original layout.

Suppose you are processing a book that measures 20 cm x 24 cm. Then you can set a `Page Box` with `Width = 200 mm` and `Height = 240 mm`, press `Apply To` and select `All pages`. If you then use `Auto Margins` the output images will measure 4724 pix x 5669 pix (which at 600 dpi means 20 cm x 24 cm) and the contents will be positioned approximately in the same place as in the original scan.

**Reference pictures**

![PageBox](https://user-images.githubusercontent.com/20274082/81087451-1ed77580-8ed0-11ea-8c1a-a5f8d9dd6602.png)    
![AutoMargins](https://user-images.githubusercontent.com/20274082/81087447-1e3edf00-8ed0-11ea-92de-55cad5d0eded.png)

**Comment by d4fe** [comment]
I do not understand what benefit this function can give in practice?

**Comment by Piolie** [comment]
The benefit you get (if used correctly) is the images in the `out` folder will have the dimensions of the physical pages, and the contents aligned in exactly the same way as the physical pages you scanned.

For some people achieving this level of fidelity is irrelevant. I personally find it very satisfying. To each its own.

**Comment by d4fe** [comment]
That is, to keep the original position of the text (and pictures) relative to the edges of the page?

**Comment by Piolie** [comment]
Yes. And also to keep the original size of the pages.
