### ISSUE TITLE
Page Thumbnail Scaling

### ISSUE THREAD

**Issue by d4fe** [4lex4/scantailor-advanced#117]
It would be convenient to be able to scale page thumbnails to the right with the scroll wheel with Ctrl held down, as was done in WinDjView (when viewing page thumbnails).
(Automatic translation).

**Comment by zvezdochiot** [comment]
What for?

**Comment by d4fe** [comment]
Zoom - to find pages with (small) images. Reduce - An overview of the maximum number for selecting pages that differ greatly in content.

**Comment by zvezdochiot** [comment]
Stupid idea.

**Comment by Piolie** [comment]
I think it's a great idea. And I guess 4lex4 also thinks it's a good idea, because [it's already implemented](https://github.com/4lex4/scantailor-advanced#scantailor-universal-fixes--improvements). It's done with `Alt+Wheel`.

**Comment by zvezdochiot** [comment]
@Piolie say:
>I think it's a great idea.

It is a pity that the commit was not indicated. How do you use this "great" function?

**Comment by d4fe** [comment]
Fine! Thanks!

**Comment by zvezdochiot** [comment]
@d4fe say:
>Fine!

But is it not supposed to close the issue in such cases?
