### ISSUE TITLE
Option to automate entire process? 

### ISSUE THREAD

**Issue by sati-bodhi** [4lex4/scantailor-advanced#118]
When operating scantailor, the user has to manually run through each of the 6 steps in order to create the final output.  

![image](https://user-images.githubusercontent.com/7592695/80274548-da98e800-870d-11ea-8ede-f32c61965138.png)

Can there be a way to automate the entire process so that a tentative output is automatically created with one click, so that, assuming the input is consistent and settings are appropriate, the user just has to make minor adjustments at the end of the procress?

**Comment by Piolie** [comment]
The very first feature requested for this project was a CLI: [scantailor-cli missing?](https://github.com/4lex4/scantailor-advanced/issues/1). I think that once that is addressed what you're asking for will be easy to do.

**Comment by d4fe** [comment]
For steps 1 to 4, you can set parameters and execute at a time.
