### ISSUE TITLE
GreyWorld filter?

### ISSUE THREAD

**Issue by zvezdochiot** [4lex4/scantailor-advanced#120]
:question: Maybe should include in the 4:“Useful area” the optional GreyWorld filter for old books?

![origin](https://i111.fastpic.ru/big/2020/0503/ed/0dc5ac81c8c005afac6970092660eced.png) to ![greyworld](https://i111.fastpic.ru/big/2020/0503/7d/5f159b6f6673343017d35fe1d5c21a7d.png)

PS: It would also be nice to have controls: brightness and contrast :low_brightness: :high_brightness:.

**Comment by jeremydmoore** [comment]
@zvezdochiot Could you provide a link to the GreyWorld algorithm you're talking about? I'm very interested.

**Comment by zvezdochiot** [comment]
Hi, @jeremydmoore 

GreyWorld algorithm:

https://github.com/ImageProcessing-ElectronicPublications/imthreshold/blob/64bbd4e5ab707b22a9b99d2ccd93ed27f769fcd9/src/lib/color.c#L407-L457

The meaning of the algorithm: calculate the average of the channels, put the resulting average "color" in line with the "gray value". The ratio of the gray value to the average of the channels will be the color coefficient.

**Comment by jeremydmoore** [comment]
Thank you,@zvezdochiot! I hadn't heard of this filter before, but I do digitization work with old materials so this is quite interesting.

**Comment by zvezdochiot** [comment]
no actual
