### ISSUE TITLE
Images in the margins?

### ISSUE THREAD

**Issue by zvezdochiot** [4lex4/scantailor-advanced#121]
:question: The pages with images on the margins:  
![scantailor](https://i111.fastpic.ru/big/2020/0502/ee/0950f2d78dc3c3f89578675dae339bee.png)  
, positioning them without a “text” block is very difficult. Can optionally enter the ability to set the "text" block?

**Comment by 4lex4** [comment]
Use guides at the margins stage, that is what they were deleloped for.
