### ISSUE TITLE
feature: fix orientation after select content behavior

### ISSUE THREAD

**Issue by AlexJacobs1977** [4lex4/scantailor-advanced#122]
I used "select content" first. Later I changed my mind to change the orientation. However, scantailor advanced doesn't recalculate the "select content" field after you change from "fix orientation" to "select content". Would it possible to change this behavior?

**Comment by jeremydmoore** [comment]
Hi Alex,

If you haven't adjusted the "select content" boxes then you should be able to select the first image that you've rotated and delete the Select Content box (right-click the box) then apply this to all of the other boxes. Now change the current box to Auto Select Content and apply to the rest of your rotated images and press play.

Now if you're wanting to change select content, adjust things, THEN change the orientation that's not an option. I've found the easiest method is to keep ALL images in a single orientation and rotate them afterwards -- or just do the images with differing orientations as 2 separate batches.

Adding the ability to rotate in the Output step (allowing one to do select content and match margins with horizontal and vertical pages) would be a huge boon for me and may also fix your issue. I believe there's an issue already submitted to add that feature.

**Comment by Piolie** [comment]
> I believe there's an issue already submitted to add that feature.

Yes, there is: [Fix orientation also at the end](https://github.com/4lex4/scantailor-advanced/issues/56).
