### ISSUE TITLE
Better support for High DPI Displays

### ISSUE THREAD

**Issue by gorgobacka** [4lex4/scantailor-advanced#124]
Today, I used a new external monitor (resolution 2560x1440) and discovered that the menus and buttons are really really small.

I'm using the Appimage on Ubuntu.

**Comment by d4fe** [comment]
I have the same, it seems to be normal.

**Comment by gorgobacka** [comment]
Here is a screenshot, how it looks like.

![Screenshot](https://user-images.githubusercontent.com/10488441/81493872-7301a180-92a4-11ea-9d7e-3f996ea2bcaf.png)

 Usually, in other applications the texts are larger. But for ST, I would need eagle eyes. :)

**Comment by d4fe** [comment]
Fonts look blurry and non-native (not matching the screen resolution). Perhaps the reason is in the system settings. I do not have this on W7.
![W7](https://user-images.githubusercontent.com/63813115/81496251-72c6cd80-92c7-11ea-800b-7ef18f285501.png)

**Comment by gorgobacka** [comment]
It seems that the described behaviour is related to using an AppImage or to the version "2019.8.16 Early Access".

I compiled the current master by myself (according to the https://github.com/4lex4/scantailor-libs-build) and it looks much better. :)

**Comment by pbakes** [comment]
Can you upload the latest build of it? I'm also having hiDPI issues with scan tailor advanced and a couple of other programs, don't have time to build it right now. Thanks
