### ISSUE TITLE
[Feature request] Add option to "Centralized the contents" within image

### ISSUE THREAD

**Issue by Nokia808** [4lex4/scantailor-advanced#126]
Hi.
I would like, at 1st, to thank you too much for this great work ...

I would like to suggest to add new feature to "centralized the contents" within image. Certain images on scan a book, will appear the contents within the image either displayed to right (left margin > right margin) or displayed to left (right margin > left). In this case - when we have different displaying from image to other in degree & direction - it will be very useful if we have an option to make contents centralized at middle of image .....

**Comment by zvezdochiot** [comment]
:question: What?

**Comment by Piolie** [comment]
Maybe what you need is one of the Alignment options?

![Align](https://user-images.githubusercontent.com/20274082/82342640-3cc0d200-99c8-11ea-9e0c-d32da0ddd200.png)

**Comment by Nokia808** [comment]
@Piolie 
Yes ! This is exactly what I was mean !

I will closed this issue. But - & to avoid open other issue - can you kindly inform me about the following: what are the allowed input files formats that can we processed by this great program? I tested it on .jpeg & worked & certainly working on .tiff Can you, kindly, give list of all supported input file formats, please?

**Comment by zvezdochiot** [comment]
https://github.com/4lex4/scantailor-advanced/blob/f6c8e5b2a2d416be224df4db600f852356ccebc3/CMakeLists.txt#L105-L108

**Comment by Nokia808** [comment]
@zvezdochiot 
Dear I'm not programmer, but I understood that the supported formats are:
1) .jpeg,
2) .png,
3) .tiff

But I did not understood is "zlib", to which format pointing ? Does it include .bmp & .pcx ?

**Comment by Piolie** [comment]
You are welcome. ZLIB is a compression library, not an image format.
Basically, what you said is correct: jpeg, png and tiff formats are supported.
