### ISSUE TITLE
[Feature request] Add support to .pcx file format input

### ISSUE THREAD

**Issue by Nokia808** [4lex4/scantailor-advanced#127]
Hi.
This great project lack the support for .pcx file format as input files. 
PCX file format is simple & very suitable for scanning & has no complex options.
It will be very useful if add support to .pcx as input files. Currently, ScanTailor Advanced not  support this file format as input files .....

**Comment by Piolie** [comment]
Not being an expert in the filed, I would say the PCX file format can be considered obsolete. I don't see it being supported in the future.

I suggest you use the PNG or TIFF formats or, if not possible, use a batch processing program to convert PCX to PNG. For example, you could try [imagemagick](https://www.imagemagick.org/) as explained [here](https://stackoverflow.com/questions/15315770/how-to-convert-all-files-in-different-formats-in-given-folder-to-different-fil).

**Comment by Nokia808** [comment]
@Piolie 
As long as some scanner devices (even recent one) still give option to save scanned images as .pcx format, then it is wise to support this format ....
