### ISSUE TITLE
How does the color of scan files affect the quality of the final result?

### ISSUE THREAD

**Issue by d4fe** [4lex4/scantailor-advanced#129]
How will the quality of the final result be affected, ceteris paribus, the type of scanning source files: 1 option - gray 8 bits, 2 color option 24 bits (3x8 = 24). Or, if asked differently, if it makes sense to scan according to option 2, instead of the first, hoping to get a better result? The output is supposed to receive a black and white image. The question is inspired by the yellow page of old books, because they are in fact colored, not gray.

**Comment by Piolie** [comment]
I think it doesn't make sense to scan in color if the end result is going to be bitonal or grayscale.

As for the yellowed pages, maybe some correction would be needed before converting to grayscale, as has been explained in #120. I have scanned some such yellowed pages in grayscale and if there was a difference it wasn't enough for me to notice.

**Comment by d4fe** [comment]
I get it. Thank!
