### ISSUE TITLE
Is there an option to disable EXIF metadata in output file(s) ?

### ISSUE THREAD

**Issue by Nokia808** [4lex4/scantailor-advanced#131]
As the title saying ....
This - if possible - can result in decrease the total output size, some thing good to achieve smaller final PDF size.

**Comment by zvezdochiot** [comment]
:question: How do you make a `PDF`? `tiff2pdf` requires a `DPI` in the image.

**Comment by Nokia808** [comment]
@zvezdochiot 
I do not know about such technical details ! Feel free to close this issue if it is technically harmful & not relevant.

**Comment by zvezdochiot** [comment]
Hi @Nokia808 .

:information_source: I am not an author. But I know enough about the manufacturing aspects of `PDF`.

When creating an issue, always specify the technical details: :question: How do you make a `PDF`?
