### ISSUE TITLE
Include dependencies in CPACK *.deb file

### ISSUE THREAD

**Issue by jeremydmoore** [4lex4/scantailor-advanced#135]
Hello,

I am trying to automate the installation of dependencies for ScanTailor Advanced using apt-get while installing in an Ubuntu Docker container, but CMakeLists.txt doesn't include the needed dependancies in the *.deb file.

Easy fix, just need to `set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)` -- pull request coming in momentarily

**Comment by 4lex4** [comment]
You don't need to change source files to manage cpack options, just use cpack -G "DEB" -D CPACK_DEBIAN_PACKAGE_SHLIBDEPS=ON, as pointed in the instruction.
