### ISSUE TITLE
Zoom content selection

### ISSUE THREAD

**Issue by Retrolab** [4lex4/scantailor-advanced#14]
I was wondering if you would consider a new feature. I have attached a mockup screenshot to show the idea. It would be nice to be able to automatically zoom the content selection so as to get a closer look at the edges of the border. It be easier to use the adjusting content area option by having the page already zoomed in.

![screen](https://user-images.githubusercontent.com/19426916/37157107-2907a562-22e8-11e8-980b-8729b677b8c5.png)

**Comment by Retrolab** [comment]
There is a nice benefit I noticed when you have good scans which are only slightly skewed. When setting the margins first before selecting the content, the content of almost every page is automatically selected without having to make any adjustments, except for a few pages. There is a remarkable difference if the margins are not set first which leaves more content on pages to be adjusted manually.

**Comment by 4lex4** [comment]
I think usual zooming is enough. Besides that the algorithm of auto detecting the page content can miss a part of the content and the auto adjusting content area feature is intended not only to shrink content but extend as well.
