### ISSUE TITLE
Indicate which page is the Largest height/width

### ISSUE THREAD

**Issue by tomse** [4lex4/scantailor-advanced#142]
Is it possible as a feature request to mark which page is the widest and which is the highest.

**Comment by Piolie** [comment]
It's already possible. In steps "Select content" and "Margins", there is a drop down list on the lower right corner to sort pages by height, width and other options.

**Comment by tomse** [comment]
Thanks, I don't know why I've never noticed that, even after having spent countless hours with the program.
