### ISSUE TITLE
[Feature Request] White Balance Output (Colour/Greyscale Mode)

### ISSUE THREAD

**Issue by mara004** [4lex4/scantailor-advanced#152]
First of all, many thanks to everybody who has contributed to this useful program!
I'd like to use a white balance feature to improve photos of book pages with a colour fault (in my case an orange tint). Perhaps parts of the code could be incorporated from an other image manipulation program like GIMP?
Maybe other features to improve colours could be added as well?

**Comment by mara004** [comment]
I managed to white-balance all my scans in an easy way with a GIMP batch processing plugin, Maybe this is out of scope for ScanTailor and other software can do better at colour correction.

**Comment by zvezdochiot** [comment]
Hi @mara004 .

See also https://github.com/log69/aaphoto
