### ISSUE TITLE
scantailor-advanced and how it relates to scantailor

### ISSUE THREAD

**Issue by a17r** [4lex4/scantailor-advanced#17]
Is this project a legitimate successor to scantailor (i.e. new upstream)? One can't help but notice that https://github.com/scantailor/scantailor/issues/121 does not go anywhere and the original repository did not receive commits for a long time. Many distributions need to make a decision very soon if they are going to drop scantailor or switch to your fork.

**Comment by 4lex4** [comment]
Try to read the readme: https://github.com/4lex4/scantailor-advanced#scan-tailor-advanced

**Comment by a17r** [comment]
Yes, I've read the readme, but I guess I should have made clearer: Did you reach out to scantailor upstream? Maybe you would get their consent to overtake the 'official' scantailor and then merge -advanced into it.

All the forkery is fine and dandy but so far has only made sure that distributions are stuck with 'old' scantailor.

*Note* that I am completely unaware of the reason why forks happened that did not merge back. I am merely inquiring as a packager who is trying to keep a package available that is otherwise in danger of being removed together with Qt4.

**Comment by 4lex4** [comment]
I'll try to explain you the situation: I need an instrument and develop it in my free time, and the other doesn't interest me. Official ST doesn't satisfy me (and not only me) as lacks some critical for processing features and doesn't give enough control over the settings. So for that reason you see STA here.
I haven't any free time on red tape or bothering with official repositories, I need to get results as fast as possible while having some free time.

**Comment by a17r** [comment]
Thanks for taking the time. We'll see if someone is still there to answer.

**Comment by 4lex4** [comment]
**a17r**, you, as a packager, might be interested in this fresh commit: 091e7b13cd545a5fa32e20c148f0c1fe2ad84642

Also see the updated build instruction following the link there.
