### ISSUE TITLE
output files should be sequentially numbered

### ISSUE THREAD

**Issue by jjYBdx4IL** [4lex4/scantailor-advanced#177]
Otherwise the order of pages is not always retained for further processing.

**Comment by Piolie** [comment]
This has already been requested in #89 and discussed in #107. However, this project has been unmaintained for some time already. It's not clear it will be further developed. Maybe try [ScanTailor Universal](https://github.com/trufanov-nok/scantailor-universal).

**Comment by jjYBdx4IL** [comment]
ty
