### ISSUE TITLE
Add new files to existing project

### ISSUE THREAD

**Issue by thomasXwang** [4lex4/scantailor-advanced#180]
Hi,
I made a project, and imported all my files from an input folder. I processed them using ScanTailor
However, I then add a few files in my input folder. 
Is there a way to add them to the existing ScanTailor project too? 

I tried "relinking", but it looks like it can only modify paths to existing files

Thank you!

**Comment by derrikF** [comment]
Right click as shown in the screenshot will help you

![Screen-2021-08-24_14-26-47](https://user-images.githubusercontent.com/4710022/130608667-bcbe516f-e80b-4eb4-ab87-3728f6dc0366.jpg)

**Comment by thomasXwang** [comment]
Thank you for your quick help, this is what I was looking for !
