### ISSUE TITLE
ImageThresholdBlur

### ISSUE THREAD

**Issue by zvezdochiot** [4lex4/scantailor-advanced#196]
Hi @4lex4 .

There is an `ImageThresholdBlur` method that is practically a transition from Otsu (BiMod) to Sauvola {0.0 ... 1.0}: https://github.com/ImageProcessing-ElectronicPublications/stb-image-djvul/blob/main/src/threshold.h .

This method only requires a Gaussian filter, a divide two images operation, and an Otsu threshold (BiMod).

Implementing it would expand the threshold adjustability (slider from 0.0 (BiMod or Otsu) to 1.0 (~Sauvola)).

If necessary, I could adapt the code of this threshold for ScanTailor, but I will not undertake to change the interface and the project file.

**Comment by leonleon33156** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zvezdochiot** [comment]
Resolved. [STEX: 0.2023.07.27: threshold](https://github.com/ImageProcessing-ElectronicPublications/scantailor-experimental/releases/tag/0.2023.07.27).
