### ISSUE TITLE
[Feature request] Descew on multiple lines of reference

### ISSUE THREAD

**Issue by juscghwe** [4lex4/scantailor-advanced#201]
Would be great if we had an option to add several lines of reference in the manual adjustments. 

_User story:
To undo the book fold I (and most of my coworkers) press down the page. This leads to 'smoother' scans as the left/right page can completely be seen and lines most of the time are clear. But we also cause several new folding lines: The one on the top from the book folding itself (concav) and a new convex line from the bottom. Sometimes these overlap, forming medium complex nets._

I made a screenshot of the resulting net from the two reference lines and highlighted the line where the net is most off. This is not the best example but I dont have a more 'extreme' at hand right now (screenshot on the bottom).
From my perspective, adding an **optional reference line in the middle** would solve this issue in most cases.

<img width="589" alt="Screenshot 2023-08-01 153913" src="https://github.com/4lex4/scantailor-advanced/assets/62502225/787986d6-67f9-46ba-b6db-b3ab49fed31e">

Also at [https://imgur.com/a/ZZKNdTm](https://imgur.com/a/ZZKNdTm)

**Comment by derycck** [comment]
This 4lex4 repository is abandoned.. Please move this feature request to https://github.com/ScanTailor-Advanced/scantailor-advanced
