### ISSUE TITLE
Move to GitLab

### ISSUE THREAD

**Issue by maximilianduell** [4lex4/scantailor-advanced#25]
The acquisition of GitHub by Microsoft and GitHub being non-free software appears to be conflict with the general philosophy and aims of this project. 
Hence it may be advisable to migrate the development repository to a completely free alternative such as e.g. gitlab, http://gitlab.com/ migration guide: https://www.youtube.com/watch?v=VYOXuOg9tQI

**Comment by 4lex4** [comment]
Yep, this is an unpleasant surprise. I need to choose between gitlab and bitbucket but a little later.
