### ISSUE TITLE
Question about using dewarp-function standalone

### ISSUE THREAD

**Issue by andersla** [4lex4/scantailor-advanced#26]
I am really impressed with the automatic dewarp function of ScanTailor, I have not seen such a function or filter in any open source image correction software.
I wonder if someone could point me in the direction of how to use this function/algorithm as a standalone feature in my automated image preparation before ocr pipeline? A pointer onto how to integrate the feature into a standalone c/python/bash program?
Or if it would be available in the future via the CLI like: `scantailor-cli --dewarp --infile myfile.png --outfile dewarped-file.png`

**Comment by 4lex4** [comment]
I have plans to re-base scantailor-cli onto default parameters feature, so it would be like this: `scantailor-cli --profile=source --until-stage=3 --dewarping-mode=MODE --out-dir=DESTINATION SOURCE...`

**Comment by 4lex4** [comment]
Relates to #1
