### ISSUE TITLE
how to start scantailor on windows7?

### ISSUE THREAD

**Issue by carlkl** [4lex4/scantailor-advanced#27]
is there an advice to start scantailor (advanced) on windows7?

nothing happens if scantailor.exe has been started from the explorer or the cmd shell.

**Comment by 4lex4** [comment]
Just install and launch from icon or scantailor.exe. Check that you've downloaded sta with right adress model.

If you still encounter this problem, input into cmd: `scantailor > log.txt 2>&1`
