### ISSUE TITLE
question about saving options

### ISSUE THREAD

**Issue by rmzV** [4lex4/scantailor-advanced#30]
hello, 4lex4!
sorry for offtop, but i have a question=/

i have scaned  my files at 3264x2448 , 24 bit color with 96 dpi [compressed png file forma] (averange file size-10mb

i'l started to save my projects at black/white  tiff 600dpi,
but now thinking to swith to color option (some of text has grayscale parts with are missssed at b&w option)
questions are: 
do i realy need 600dpi,  or 300dpi will be enought? according to my input file?
color mode gives me 100 mb(at 600dpi)  per page file sizes, any options how to compress them better?

thank you

may be there are is any other lossless option to store this 120mb tiff files for archiving purpose?

**Comment by rmzV** [comment]
ok i found solution. "pasterise" will do the trick.
so question is not legit now.


will 0.15 version have a portable edition?

**Comment by 4lex4** [comment]
96 DPI is not a valid value, it means you must enter correct dpi in the Fix DPI dialog. According to the resolution your source file is probably of 300 DPI, you should learn what DPI means. 

You did it wrong, posterization is for other purposes. 

The second question is described in the readme, all the versions are portable.

**Comment by 4lex4** [comment]
96 or 72 DPI are not valid values and mean no info, it means you must enter the correct dpi value in the Fix DPI dialog. According to the resolution your source file is probably of 300 DPI, you should learn what DPI means. 

You did it wrong, posterization is for other purposes. 

The second question is described in the readme, all the versions are portable (you can just unpack the installer or install with that into a custom non-system path).

**Comment by rmzV** [comment]
ill upload default image of A4 paper, can you check it please?
https://dropmefiles.com/BOsnk

"irfanview" says its 96 dpi
but:
 i measured vertical dimension of a4 paper in "paint" and it is 1600pixels 
so 21cm to inches = 8.27inches
and 1600/8.27 = 193 = aprox 200 dpi
so my dpi = 200??

**Comment by 4lex4** [comment]
> i measured vertical dimension of a4 paper in "paint" and it is 1600pixels
> so 21cm to inches = 8.27inches
> and 1600/8.27 = 193 = aprox 200 dpi
> so my dpi = 200??
Yep.
