### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by bup4gr** [4lex4/scantailor-advanced#33]
Is it possible to add a portable version of scantailor advanced (now only exe)?

**Comment by rmzV** [comment]
@bup4gr , you can install scantailor on on PC and then move this folder(with installed ST) to another PC

**Comment by bup4gr** [comment]
It's a possibility, but for me it's better to add a portable version in https://github.com/4lex4/scantailor-advanced/releases.

In this way:
- no installation
- no unnecessary registry entries

**Comment by 4lex4** [comment]
Just unpack the installer as an archive file.

**Comment by bup4gr** [comment]
Thank you. I unpacked the exe with 7-zip. Then i deleted `$pluginsdir` and `uninstaller.exe`.
But in my opinion, as i said, it's better to add a portable version in https://github.com/4lex4/scantailor-advanced/releases.
