### ISSUE TITLE
scantailor suspended

### ISSUE THREAD

**Issue by matnawi72** [4lex4/scantailor-advanced#35]
![scantailor suspended](https://user-images.githubusercontent.com/40972294/43736966-e43b81f4-997c-11e8-9174-75fae2d9342f.png)

**Comment by matnawi72** [comment]
scantailor get stuck suddenly and when I check task manager it says suspended. I tried many times to close it and open it but same issue. even I restarted my computer and still the same issue. it's the 1st time I have this problem.

**Comment by 4lex4** [comment]
Duplicates #63
