### ISSUE TITLE
Problem with black background instead of white

### ISSUE THREAD

**Issue by Tapter** [4lex4/scantailor-advanced#36]
Hi
I have a page with a lot of (dark) images and very little text. I'm struggling to get ScanTailor to chose a white background (for the margins) in this scenario.
I've selected 'mixed' mode because of the images. I'd expect that the 'Filling - Color: white' would do exactly that - however it does nothing (and there's no tooltip describing this property).
There's another related: 'Processing -> Black on white mode' which seems to help..
Could you explain how the two properties are related and which would be the preferred to fix this situation? Also, why isn't the 'black on white mode' selected by default - I'd assume that most books are indeed black on white?
![image](https://user-images.githubusercontent.com/17089359/43808205-44ac5560-9aac-11e8-82bc-b0a06d485cb9.png)

Here's the input image:
https://user-images.githubusercontent.com/17089359/43808165-0869927a-9aac-11e8-9ece-d79a20fec76b.jpg

Thanks
Matt

**Comment by derrikF** [comment]
Use the Processing as highlighted in the screenshot
![test](https://user-images.githubusercontent.com/4710022/43847256-d8fdf17e-9b38-11e8-99ee-2a1c621cfa20.jpg)

**Comment by mkeller-ergon** [comment]
So having this checkbox checked effectively enforces black on white, while having it disabled means someting like 'auto detection' ?
What exactly is the meaning of 'Filling - Color: white' then? There's no tooltip unfortunately, so I don't understand what it's for...
Thanks

**Comment by derrikF** [comment]
you just need to remember - use this option when the fields are still filled not with white, but with black...

there is no other solution so far, so this is a temporary solution to this problem...

**Comment by 4lex4** [comment]
Just disable this feature in _Settings -> Processing -> **Auto detect light content on light background**_ before making a project without text and images only.
You can disable that for good of course but ST will be unable to correctly deskew, find content and so on on pages with dark background and you'll have to do that manually. Adaptive binarization, normalize illumination and almost all output algorithms wont work correctly on such pages without this feature as well but at the output stage you can still enable it manually via checkbox.
