### ISSUE TITLE
Packaging for Linux

### ISSUE THREAD

**Issue by ALTracer** [4lex4/scantailor-advanced#42]
Couldn't find binary packages for Debian, so I have just followed your "Compile from source" faq under Linux Mint 19 (Ubuntu). 

1. We have libjpeg-dev in our repos, which is a meta for libjpeg8-turbo-dev, yet you demand libjpeg9-dev, which conflicts with libjpeg8-dev -- but it is required by libtiff5. Nevertheless, jpeg functionality is intact (just completed a book).

2. `cpack -g "DEB"` successfully forges a Deb package, but writes no dependencies. How are we supposed to know to install libqt5gui5, libqt5xml5, libqt5core5a, libpng16-16, libjpeg8 etc. without visiting your github project page? You may provide CPACK_ flags(variables) to solve this.

3. I agree many users have `gcc-7, g++-7, lib*-dev, cmake` and X11/pictureformat dev.libs installed on their linux boxes. Still, would you please publish .deb and .rpm for i686,amd64,armhf into releases?

**Comment by hason** [comment]
@ALTracer I prepared a recipe for binary package for Arch linux - https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=scantailor-advanced

**Comment by ALTracer** [comment]
@hason There is a Gentoo .ebuild  https://packages.gentoo.org/packages/media-gfx/scantailor-advanced as well. But Arch and Gentoo are "compile from source" distros, and that's their default way even if binary packages are available. However, many people choose APT or RPM-based distros (Ubuntu/Fedora...) due to lack of time for configuring, compiling packages, resolving dependencies manually etc. 
All I ask is release .DEBs and .RPMs with written dependencies together with Windows MSI Installers/ZIP portables. Hell, I could even provide a machine or service for compiling them for some architectures.

**Comment by sojusnik** [comment]
At least a .deb package is still very appreciated. A flatpak would be more universal though.

**Comment by 4lex4** [comment]
For DEB and RPM see: https://github.com/4lex4/scantailor-libs-build#packaging

**Comment by thibaultmol** [comment]
@4lex4 are you planning to add the prebuilt binaries to the releases? (think that would be handy for people that are too afraid of compiling code for some reason)
