### ISSUE TITLE
Impossibly small (non working) UI widgets on Linux Mint

### ISSUE THREAD

**Issue by artelse** [4lex4/scantailor-advanced#49]
I have been trying out my just compiled Linux Mint version and run up against UI widgets that are so small one can hardly work with it. Drop downs often do not work when clicking on them. However, when I move the window to my smaller laptop screen from my external monitor, the widget not only are bigger, but also just work.
So it seems a scaling factor is at play in relation to the screen size? Is there a way to fix these impossibly small widgets?
Attached a photo of the issue. Note the size of the mouse pointer in relation to the widgets and my terminal window on the left
![img_1423](https://user-images.githubusercontent.com/787801/49856725-e160dc80-fdf0-11e8-8652-984628c4c315.JPG)
.

**Comment by 4lex4** [comment]
Try to choose the native color scheme in the settings.

**Comment by artelse** [comment]
That was my initial thought as well, but it makes no difference, menus and widgets remain small. Of note is that starting up STA in native mode, it doesn't report the "drawbase" property missing from my other issue.
Any ideas?

**Comment by 4lex4** [comment]
Write something here if you are still interested to solve the issue.
