### ISSUE TITLE
Feature Request: Check for a Blank Pages on Output Stage

### ISSUE THREAD

**Issue by iz7iz7iz** [4lex4/scantailor-advanced#5]
On the output state, It would be useful to check for a blank page.

this way the page will be complete white/blank and there will be no potential for small obstacles/despeckling areas.

The blank/white page should be the same size as the other pages.

**Comment by 4lex4** [comment]
This feature seems to have been realized already, but doesn't work due to ST resets empty content rectangle to page bounds. After fixing that behavior it should be ok.

**Comment by 4lex4** [comment]
a51483eedd8b4bcec8418d964fc5010109d193ba

**Comment by 4lex4** [comment]
#a51483eedd8b4bcec8418d964fc5010109d193ba

**Comment by 4lex4** [comment]
@4lex4
a51483eedd8b4bcec8418d964fc5010109d193ba

**Comment by 4lex4** [comment]
a51483eedd8b4bcec8418d964fc5010109d193ba

**Comment by 4lex4** [comment]
4lex4@a51483eedd8b4bcec8418d964fc5010109d193ba

**Comment by 4lex4** [comment]
#5 a51483eedd8b4bcec8418d964fc5010109d193ba
