### ISSUE TITLE
Packaging for Mac

### ISSUE THREAD

**Issue by maxwacker1** [4lex4/scantailor-advanced#51]
Couldn't find a Compile version for Mac.

**Comment by yb85** [comment]
https://github.com/yb85/scantailor-advanced-osx
not tested yet, feedback welcome to know if it works properly

**Comment by lifepillar** [comment]
@yb85 I was able to build ScanTailor 1.0.16 with your formula in macOS High Sierra (10.13.6) without issues. The app appears to work fine (still struggling with the controls, especially right-click vs ctrl-click, but that is a ScanTailor issue…). I encourage you to submit your formula for inclusion into Homebrew. Anyway, thank you very much!

**Comment by 4lex4** [comment]
**yb85**, nice work, I've added the link to the readme
