### ISSUE TITLE
How to compile on trusty or xenial?

### ISSUE THREAD

**Issue by probonopd** [4lex4/scantailor-advanced#59]
Getting

```
CMake Error at /usr/local/cmake-3.12.4/share/cmake-3.12/Modules/FindBoost.cmake:2048 (message):
  Unable to find the requested Boost libraries.
  Boost version: 1.58.0
  Boost include path: /usr/include
  Detected version of Boost is too old.  Requested version was 1.60 (or
  newer).
```

How to compile on trusty or xenial?

References:
* https://github.com/probonopd/scantailor-advanced/blob/patch-1/.travis.yml
* https://travis-ci.com/probonopd/scantailor-advanced/builds/109090448

**Comment by derrikF** [comment]
https://github.com/4lex4/scantailor-libs-build#building-from-sources --> 6. Build boost:

**Comment by probonopd** [comment]
Thanks, I have managed to get it built using

```
sed -i -e 's|Boost 1.60|Boost 1.50|g' CMakeLists.txt
```

AppImages for testing:
https://github.com/probonopd/scantailor-advanced/releases

**Comment by probonopd** [comment]
Thanks. How can we get https://github.com/4lex4/scantailor-advanced/pull/60 merged @4lex4?

**Comment by 4lex4** [comment]
I'll modify and merge that with develop branch later. Now it misses qt5 svg.

**Comment by probonopd** [comment]
Adding `qt59svg` to https://github.com/4lex4/scantailor-advanced/pull/60/files#diff-354f30a63fb0907d4ad57269548329e3R11 should do the trick.

**Comment by 4lex4** [comment]
@probonopd the main question is what your `upload.sh` will do with my release page ([this part](https://github.com/4lex4/scantailor-advanced/pull/60/commits/d1e3cf5d73db30809248d1e66e7513b34ea02302#diff-354f30a63fb0907d4ad57269548329e3R25-R32)).
As you can see I work on the project in the `develop` branch and merge that with `master` only on releasing a new version.
And I don't want to break the releases structure by `Continuous build` on the top with the only asset which is the unversioned AppImage file (although this part I can fix myself by adding to the script extraction the version from version.h). As you can see my releases are tagged and contain version, changelog and assets containing, inter alia, binaries for windows. I need the AppImage file to be there along with the other assets and nothing more.

**Comment by probonopd** [comment]
> As you can see I work on the project in the develop branch and merge that with master only on releasing a new version.

Where would you like continuous builds for the develop branch to be uploaded to?

**Comment by 4lex4** [comment]
@probonopd, it could be any place but not the main release page, and I don't know whether github allows to show a release only for one branch. Even if that does I'd like to make deploying only on tagged builds: https://docs.travis-ci.com/user/deployment/releases/#deploying-only-on-tagged-builds

**Comment by probonopd** [comment]
You can build and upload for tagged builds only if you want, just replace my `uploadtool` calls with the native releases providers from Travis CI.

Nevertheless I personally find it very useful to always have a binary for every build (only the last successful build is kept).
