### ISSUE TITLE
[enhancement] diy book scanning

### ISSUE THREAD

**Issue by qBittorentUser** [4lex4/scantailor-advanced#6]
Hello,

I want to thank to develop scan tailer further. 

The program is intented for regular scanners. However, I use a camera to picture the pages of the book. I photograph the uneven pages first, then the even pages. To sort the pages, I use a small tool called RenameAll from this website: http://www.instructables.com/id/Bargain-Price-Book-Scanner-From-A-Cardboard-Box/ It would be great if scan tailer had such a feature, it would mean using only one program instead of two. I'm quite sure such a feature would make DIY book scanners like me very happy.

Thank you for considering this.

**Comment by 4lex4** [comment]
I think renaming is out of scope of this project. There are many programs to do batch renaming, ex.,  besides it can be made by a simple script.
