### ISSUE TITLE
Height/Width Ratio Changes on Ouptut

### ISSUE THREAD

**Issue by dyacob** [4lex4/scantailor-advanced#62]
Greetings,

This is a support question but may also relate to feature request #7.  I just started using ScanTailor Advanced on Windows 10 and its great.  I have an issue on the final step for Output. Page images look excellent on the Margins step, but when output is generated the height and width of the image appears to have been scaled to new proportions, looking distorted.

I'd like the height/width ratio to remain the same in the output files.  What setting is making these proportions change from what is seen in the Margins step?

thanks,

-Daniel

**Comment by konos93** [comment]
hello is that video from 6.00 and after helpful ? https://www.youtube.com/watch?v=l_wxUJFEZLI

**Comment by 4lex4** [comment]
Could you provide any project example with a distorted image at 4lex49@zoho.com

**Comment by dyacob** [comment]
Sorry for the belated response.  The issue  came from my misunderstanding of the Fix DPI dialog.  I had set a Custom DPI that matched the pixel setting of the image (5152x3864).  This caused the skewing.  Thanks!
