### ISSUE TITLE
Output Processing time: 

### ISSUE THREAD

**Issue by jtpf** [4lex4/scantailor-advanced#66]
In the output step, It takes 2 min to process one page. It is too long! Is there any way to process fast?
My computer is 2 hexa xeon processors (24 cores) and 36 GB Ram!

Thanks for your help

**Comment by darnn** [comment]
You may not have the proper DPI set in the image files you're importing. ScanTailor Experimental ignores DPI so I forgot it was even a concern, but it is. Check "fix dpis even if they look okay" when importing your files, and apply the appropriate DPI to all pages. For me that's usually 300x300 or 600x600, but I'm sure you'll figure it out.
