### ISSUE TITLE
How does this version compare to ScanTailor Universal?

### ISSUE THREAD

**Issue by ylluminarious** [4lex4/scantailor-advanced#78]
I see that this version attempts to unite ScanTailor Featured and ScanTailor Enhanced with new fixes for both. I am curious, however, to know how this version compares to [ScanTailor Universal.](https://github.com/trufanov-nok/scantailor) I was initially under the impression that this version included changes from ScanTailor Universal, but upon closer inspection I am not sure if this is the case. If I am incorrect about this, I would like to know. But if this version is separate and distinct from ScanTailor Universal, I would like to know how both compare. I am just curious to find out whether the two have different feature-sets.

**Comment by rramphal** [comment]
I tried to make this comparison happen last year, but it didn't really gain traction. It would be great to have it added to a GitHub repo wiki so others can help keep it up to date. Perhaps it might be useful to you as a starting point?

https://forum.diybookscanner.org/viewtopic.php?f=21&t=3504

**Comment by ylluminarious** [comment]
@rramphal Thanks a lot for those comparisons! It seems ScanTailor Advanced is more featureful than Universal... is this true or has Universal integrated changes from Advanced which put the two on more equal footing? I'm not quite sure which one to use since Universal seems more active, but Advanced also seems maybe more featureful.

**Comment by ylluminarious** [comment]
@rramphal The author of ScanTailor Universal provided some valuable insights and comparisons between several forks [in his comment here...](https://github.com/trufanov-nok/scantailor/issues/63#issuecomment-539079863) you might want to add his remarks to your forum post and whatnot.
