### ISSUE TITLE
Can not apply manual content area to the following pages

### ISSUE THREAD

**Issue by ermylistru** [4lex4/scantailor-advanced#8]
Encounted that I can not apply manual content area to the following pages, if they already have manual content area.
If I want to apply a different content area from some page to all following pages, only 4-5 pages following the source page are changed at first, and then - only one page is changed.
The program is very nice as it works much faster due to multicore usage, but this bug made me switch back to ScanTailor Featured, which is working OK. 
Its a pitty. Could you please look into it?

**Comment by 4lex4** [comment]
Bring me the project file and some examples so I could replay the bug.

**Comment by ermylistru** [comment]
Thanks for the reply.. ))
Will do it as soon as possible tomorrow..
Regards, Viacheslav. суббота, 13 января 2018г., 05:22 +03:00 от 4lex4  notifications@github.com :

**Comment by 4lex4** [comment]
No project file or examples needed, I seem to have understood your problem.
You've just forgot to check the "Apply content box" checkbox in the dialog.

**Comment by ermylistru** [comment]
Dear 4lex4,

Sorry for delay in answering you. 
Already deleted the project, so needed to make another one and experiment a bit to make it show this behaviour.
Yes, it is the first thing I thought about - that I missed something, but I checked this checkbox all the time - I paid much attention to not forget it. )

See attached the project with pics.
Actually I could not find any common denominator in the behaviour - it just behaves strange - misses pages (not applies content box to some of them), sometimes not applies anything at all and so on.
Previous time it just applied content box to 4 and then to 1 following page, now it was different.
But what i noticed it works OK if pages are the same size, but it they are different sizes, it starts to behave strangely.
Sometimes if I choose content box on a big page and its border goes beyond other smaller pages ends, it doesn't change the boxes.
I thought that it is the reason, but the next time after I apply a small box, everything begins to work fine.
So, i don't know - maybe you will see something from my project.

But it looks like that it shows itself only on some very particular files or something. So maybe it is not very general and harmful problem.
Anyway the program is wonderful, as far as this thing won't be poping all the time.. ))

Regards, Viacheslav.

**Comment by 4lex4** [comment]
ermylistru, please read my previous message, you've missed that. I've highlighted what you should do with bold.

**Comment by 4lex4** [comment]
More info in Russian:
https://www.forum.ru-board.com/topic.cgi?forum=5&bm=1&topic=32945&start=2126&limit=5

**Comment by ermylistru** [comment]
Sorry, do you mean this message?
No project file or examples needed, I seem to have understood your problem.
You've just forgot to check the "Apply content box" checkbox in the dialog.
I read that and checked this box - i mentioned that in the letter.
Or you wrote smth else? Haven't received anything more.. sorry..
Viacheslav. воскресенье, 14 января 2018г., 06:28 +03:00 от 4lex4  notifications@github.com :

**Comment by 4lex4** [comment]
Sorry, it was my miss. :)
I've remember that issue, that I've found myself and fixed a month ago.

The issue is that if we have a large page with a large content box which is followed by a small one, the content will be trimmed even for the other pages following that small page.

The fix will be available in version 1.09.

Ty for useful report, feel free for reporting any issues.

**Comment by ermylistru** [comment]
Вы на русском я так понял говорите?
Зря тогда пишу мучаюсь по английски получается.. ))
Почитал форум.. но прикол в том, что я как и написал, нажимаю эту галку применить область, постоянно нажимаю..) хотя конечно утомляет это, но что делать..)
И все равно странно себя как то ведет.. непонятные пропуски страниц, то где то меняет области, то не меняет и пр.
Ну буду еще работать, буду смотреть. Если что конкретнее будет напишу.
А проект мой подвигайте области, поприменяйте к этой и последующим страницам, может у вас тоже это проявится.
Спасибо.
Вячеслав. воскресенье, 14 января 2018г., 06:38 +03:00 от 4lex4  notifications@github.com :

**Comment by 4lex4** [comment]
Да баг это, все вспомнил. Если за большой страницей с большой областью контента следует маленькая страница, то при применении она обрежется для всех страниц, следующих за этой маленькой страницей.
Я эту проблему сам нашел месяц назад и профиксил тогда же, но фикс будет доступен только в версии 1.09.

Галку я сделаю включенной по умолчанию.

**Comment by ermylistru** [comment]
Отлично.. спасибо..)
Да, похоже на что-то типа того.. ))
У меня тоже тока на страницах, которые сильно в размерах отличаются проявляется, а если чуть чуть, то все ок. Тогда область до края не доходит наверное.
Ну круто.. спасибо вам за программу.. а то ждать на одном ядре совсем замучался.. очень хотелось, чтобы кто то сделал.. да и круто вы собрали все функции в одну кучу.. просто супер..
И на Qt сделали - тоже на нем пописываю маленько, хорошая штука.
Про галку по умолчанию - это тоже было бы хорошо, а то если часто вручную зоны расставляешь выделять ее реально утомляет.. )
Ну удачи вам тогда..)
Вячеслав.
воскресенье, 14 января 2018г., 07:02 +03:00 от 4lex4  notifications@github.com :

**Comment by 4lex4** [comment]
Нашел я фикс, оказывается, это было 27 ноября, то есть в версии 1.08 этого бага уже нет.
В какой версии вы столкнулись с этим багом?

**Comment by ermylistru** [comment]
Хмм.. скачал программу несколько дней назад, думаю версия последняя, какая сейчас есть.. завтра могу точно посмотреть.
Ну да, вполне возможно это что то другое - в моем наблюдении и правда поведение более сложное, чем просто трим по меньшей странице всех последующих..
Там есть страницы на которых вообще зоны остаются прежние. Если маленькую зону делаешь, то проблем нет - все меняется, а в большую стороны как то странно.. по разному.
Могу видео снять завтра..
Вячеслав. воскресенье, 14 января 2018г., 07:35 +03:00 от 4lex4  notifications@github.com :

**Comment by 4lex4** [comment]
Ок, тогда жду видео.

**Comment by ermylistru** [comment]
Ок, постараюсь сегодня до вечера записать видео.
Версия программы - 1.08 PR.

Тут возникло у меня несколько мыслей в целом о программе СканТейлор, пока не забыл решил написать - вдруг будет вам это интересно.

Я довольно плотно занимался оцифровкой книг последние несколько лет, оцифровал несколько сотен книг уже наверное, для этих целей пользовался разными Скан тейлорами, скан кромсатором, Фотошопом (более-менее владею), Djvu small mod, Imager, FineReader и пр. программами - т.е. небольшой опыт пользователя есть.

Скан тейлор очень удобная и визуальная программа, со всеми нужными функциями - отделение картинок от чб текста на одной странице в Featured особенно круто и прочее - ну практически все есть, что нужно.. супер.. особенно в вашей версии - многоядерность - работает реально как самолет по сравнению с оригиналом и пр.

В отличие от того же скан кромсатра, который мне не очень нравится - неочевидный интерфейс, некоторые возможности не явно видны, все как то неудобно и пр.

Но вы знаете, всем хорош скан тейлор, кроме одного, из-за чего все же иногда приходится использовать скан кромсатор.

То, что он (скан тейлор) изменяет жирность текста при выводе - как ни крути этот ползунок тоньше-жирнее - все равно на выходе точно что в оригинале не получишь - то жирнее, то тоньше текст.. 
а иногда это весьма критично. на хороших текстах может нет, а на плохих бывает важно.. да и на хороших, когда хочется сохранить аутентичность шрифта. Все же при ожирнении или утоньшении сильно внешность шрифта меняется.

Плюс на разных страницах толщина шрифта разная - эту настройку приходится проверять по всему документу, и к разным страницам разную выбирать, а то где-то вроде нормально, а на других страницах жирный текст слипся, или тонкий пропал - долго это и непредсказуемо, если все страницы не просматривать.

В сканкромсаторе вот такой болезни нет - выводит точно, что было.
Возможность ужирнения/утоньшения текста это хорошо, несомненно, но хотелось бы чтобы в 0 было точно как в оригинале.

Также я думаю, что скантейлор, сканкромсатор - программы в основном для резки текста, выделения областей, приведения страниц к одному размеру - формированию книги. Изменение разрешения, манипуляции с резкостью, перевод в чб, вывод файлов - это некоторая их вторая функция. 
Эту функцию могут легко решать - и иногда лучше и с большими настройками и возможностями и другие программы вроде фотошопа и пр.

Я часто финально обрабатываю фотошопом, дополнительно накладывая разные фильтры, улучшающие текст и пр. - результат бывает лучше..
иногда результат лучше, если изменять разрешение и переводить в чб непосредственно самим djvu конвертером, ну и т.д.

В этом плане мне не очень нравится функция перевода серого изображения из 24 бит в 8 по умолчанию при выводе - хотелось бы оставлять как есть в оригинале, либо чтобы был выбор - чб, серое, цветное, смешанное - типа того.

Мне кажется, что разделение на эти две функции хорошо бы иметь ввиду при развитии программы..
Хорошо бы чтобы была возможность сделать первое и не применять ничего из второй группы, оставив все в оригинальном виде, чтобы остальные манипуляции провести где-то еще..
В принципе сейчас это можно отлично сделать, кроме принудительного перевода в оттенки серого.

Вот такие есть мысли, может как-то поможет что-то улучшить. ))

Вячеслав.

**Comment by 4lex4** [comment]
Отключите обе галочки сглаживания и используйте адаптивные алгоритмы бинаризации. В версии 1.08 переключение на адаптивные алгоритмы сломано, т. е. при переключении будет юзаться неадаптивный оцу, в 1.05 работает, тестируйте выход на ней.

**Comment by ermylistru** [comment]
Вот, снял видео..
Проявилось поведение.. 
https://youtu.be/zXFxPnIImww  

В первом кусочке все страницы применились кроме одной..
В остальных двух - область применяется всего к нескольким следующим страницам, остальные не изменяются.

Вячеслав.

**Comment by 4lex4** [comment]
ermylistru, скиньте проекты с картинками на ![mail](https://user-images.githubusercontent.com/16573106/34945822-b20f43e8-fa15-11e7-90f9-40213737e960.png)

**Comment by ermylistru** [comment]
Я вам уже скидывал этот проект в одном из предыдущих писем..
Там проявляется не всегда, а в непонятной последовательности - мне приходилось чтобы воспроизвести данное поведение несколько раз создавать с этими картинками новый проект - в начале глючит как на видео, потом через какое-то время начинает работать нормально, когда по всем страничкам пройдешься..
Открываешь фотки заново в новом проекте - опять начинает глючить, но не каждый раз..
Вячеслав. понедельник, 15 января 2018г., 17:01 +03:00 от 4lex4  notifications@github.com :

**Comment by 4lex4** [comment]
ermylistru, а куда вы скинули то? На гитхаб нельзя скинуть, если вы приаттачили проект к письму - то аттач просто пропал, гитхаб показывает только текст.
